<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE liga [
        <!ELEMENT liga (partido)*>
        <!ELEMENT partido (equipos|resultados)*>
        <!ELEMENT equipos (equipo)+>
        <!ELEMENT equipo (goles)*>
        <!ATTLIST equipo
                juegaEn (casa | visitante) #REQUIRED>
        <!ELEMENT goles (gol)*>
        <!ELEMENT gol (jugador|minuto)*>
        <!ELEMENT jugador (#PCDATA)>
        <!ELEMENT minuto (#PCDATA)>
        <!ELEMENT resultados (#PCDATA)>
        ]>
<liga>
    <partido>
        <equipos>
            <equipo juegaEn="casa">
                <goles>
                    <gol>
                        <jugador/>
                        <minuto/>
                    </gol>
                </goles>
            </equipo>
            <equipo juegaEn="visitante">
                <goles>
                    <gol>
                        <jugador/>
                        <minuto/>
                    </gol>
                </goles>
            </equipo>
        </equipos>
        <resultados/>
    </partido>
</liga>